import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';
import { useState, useEffect } from 'react';

const Home: NextPage = () => {
  const [stats, setStats] = useState('');
  const getCurrentStats = async () => {
    const result = await fetch('http://localhost:3000/api/getCurrentStats');
    const stats = await result.json();
    setStats(stats);

    console.log('stats', stats);
  };

  return (
    <>
      <Head>
        <title>LeBron tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>
            Lebron <span className={styles.pinkSpan}>Tracker</span>
            <button onClick={getCurrentStats}>get scores</button>
          </h1>
        </div>
      </main>
    </>
  );
};

export default Home;
